platform :android do
  desc "Deploy to Play Store Internal Testing"
  lane :deploy_internal do
    upload_to_play_store(
      json_key: ENV["PLAY_STORE_CONFIG_JSON_PATH"] || File.join(Dir.pwd, "play-store-credentials.json"),
      track: "internal",
      aab: ENV["AAB_PATH"] || "../app/build/outputs/bundle/release/app-release.aab",
      mapping_paths: [ENV["NATIVE_DEBUG_SYMBOLS_PATH"] || "../app/build/outputs/native-debug-symbols/release/native-debug-symbols.zip"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )
  end

  desc "Promote Internal to Production"
  lane :promote_to_production do
    upload_to_play_store(
      json_key: ENV["PLAY_STORE_CONFIG_JSON_PATH"] || File.join(Dir.pwd, "play-store-credentials.json"),
      track: "internal",
      track_promote_to: "production",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
